import React from 'react'
import { Button } from 'joey'
import css from '../Buttons.module.css'

export default function InverseButtons() {
    function handleClick() {
        console.log('Test button clicked')
    }
    return (
        <div>
            <Button
                className={css.button}
                size="md"
                color="#1B1C1D"
                onClick={handleClick}
                inverse
            >
                Black
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#767676"
                onClick={handleClick}
                inverse
            >
                Gray
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#A5673F"
                onClick={handleClick}
                inverse
            >
                Brown
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#DB2828"
                onClick={handleClick}
                inverse
            >
                Red
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#F2711C"
                onClick={handleClick}
                inverse
            >
                Orange
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#FBBD08"
                onClick={handleClick}
                inverse
            >
                Yellow
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#21BA45"
                onClick={handleClick}
                inverse
            >
                Green
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#00B5AD"
                onClick={handleClick}
                inverse
            >
                Teal
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#2185D0"
                onClick={handleClick}
                inverse
            >
                Blue
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#6435C9"
                onClick={handleClick}
                inverse
            >
                Violet
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#A333C8"
                onClick={handleClick}
                inverse
            >
                Purple
            </Button>
            <Button
                className={css.button}
                size="md"
                color="#E03997"
                onClick={handleClick}
                inverse
            >
                Pink
            </Button>
        </div>
    )
}